In [1]:
from src.load_data.load_data import load_data

path = '../data/raw/airbnb.csv'

raw_df = load_data(path)

In [5]:
raw_df.head()

,Unnamed: 0,id,name,rating,reviews,host_name,host_id,address,features,amenities,...,price,country,bathrooms,beds,guests,toiles,bedrooms,studios,checkin,checkout
0,0,49849504,Perla bungalov,4.71,64,Mehmetcan,357334205.0,"Kartepe, Kocaeli, Turkey","2 guests,2 bedrooms,1 bed,1 bathroom","Mountain view,Valley view,Lake access,Kitchen,...",...,8078,Turkey,1,1,2,0,2,0,Flexible,12 00 pm
1,1,50891766,Authentic Beach Architect Sheltered Villa with...,New,0,Fatih,386223873.0,"Kaş, Antalya, Turkey","4 guests,2 bedrooms,2 beds,2 bathrooms","Kitchen,Wifi,Dedicated workspace,Free parking ...",...,4665,Turkey,2,2,4,0,2,0,4 00 pm - 11 00 pm,10 00 am
2,2,50699164,cottages sataplia,4.85,68,Giorgi,409690853.0,"Imereti, Georgia","4 guests,1 bedroom,3 beds,1 bathroom","Mountain view,Kitchen,Wifi,Dedicated workspace...",...,5991,Georgia,1,3,4,0,1,0,After 1 00 pm,12 00 pm
3,3,49871422,Sapanca Breathable Bungalow,5.0,13,Melih,401873242.0,"Sapanca, Sakarya, Turkey","4 guests,1 bedroom,2 beds,1 bathroom","Mountain view,Valley view,Kitchen,Wifi,Free pa...",...,11339,Turkey,1,2,4,0,1,0,After 2 00 pm,12 00 pm
4,4,51245886,Bungalov Ev 2,New,0,Arp Sapanca,414884116.0,"Sapanca, Sakarya, Turkey","2 guests,1 bedroom,1 bed,1 bathroom","Kitchen,Wifi,Free parking on premises,TV,Air c...",...,6673,Turkey,1,1,2,0,1,0,After 2 00 pm,12 00 pm

In [3]:
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12805 entries, 0 to 12804
Data columns (total 23 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    12805 non-null  int64
 1   id            12805 non-null  int64
 2   name          12805 non-null  object
 3   rating        12805 non-null  object
 4   reviews       12805 non-null  object
 5   host_name     12797 non-null  object
 6   host_id       12805 non-null  float64
 7   address       12805 non-null  object
 8   features      12805 non-null  object
 9   amenities     12805 non-null  object
 10  safety_rules  12805 non-null  object
 11  hourse_rules  12805 non-null  object
 12  img_links     12805 non-null  object
 13  price         12805 non-null  int64
 14  country       12805 non-null  object
 15  bathrooms     12805 non-null  int64
 16  beds          12805 non-null  int64
 17  guests        12805 non-null  int64
 18  toiles        12805 non-null  int64
 19  bedrooms      12805 non-null  int64
 20  studios       12805 non-null  int64
 21  checkin       12005 non-null  object
 22  checkout      10355 non-null  object
dtypes: float64(1), int64(9), object(13)
memory usage: 2.2+ MB

In [6]:
raw_df.drop(columns=['Unnamed: 0', 'id', 'name', 'host_name', 'host_id', 'features', 'safety_rules', 'hourse_rules', 'img_links', 'checkin', 'checkout'], inplace=True)

In [7]:
raw_df

,rating,reviews,address,amenities,price,country,bathrooms,beds,guests,toiles,bedrooms,studios
0,4.71,64,"Kartepe, Kocaeli, Turkey","Mountain view,Valley view,Lake access,Kitchen,...",8078,Turkey,1,1,2,0,2,0
1,New,0,"Kaş, Antalya, Turkey","Kitchen,Wifi,Dedicated workspace,Free parking ...",4665,Turkey,2,2,4,0,2,0
2,4.85,68,"Imereti, Georgia","Mountain view,Kitchen,Wifi,Dedicated workspace...",5991,Georgia,1,3,4,0,1,0
3,5.0,13,"Sapanca, Sakarya, Turkey","Mountain view,Valley view,Kitchen,Wifi,Free pa...",11339,Turkey,1,2,4,0,1,0
4,New,0,"Sapanca, Sakarya, Turkey","Kitchen,Wifi,Free parking on premises,TV,Air c...",6673,Turkey,1,1,2,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
12800,4.94,16,"Imhoe-myeon, Jindo, South Jeolla Province, Sou...","Kitchen,Wifi,Free parking on premises,Private ...",4288,South Korea,8,0,4,0,0,0
12801,4.67,6,"Gianyar, Indonesia","Wifi,Free on-street parking,Air conditioning,G...",15200,Indonesia,0,1,2,1,1,0
12802,4.67,3,"Kabale, Uganda","Wifi,Breakfast,Long-term stays allowed,Unavail...",9103,Uganda,1,2,2,0,1,0
12803,4.86,7,"Gunung Sari, Nusa Tenggara Barat, Indonesia","Kitchen,Wifi,Dedicated workspace,Free parking ...",42262,Indonesia,2,4,8,0,2,0
12804,4.85,13,"Uruma, Okinawa, Japan","Sea view,Beach access – Beachfront,Kitchen,Wif...",9909,Japan,1,2,5,0,1,0