In [2]:
from src.load_data.load_data import load_data

path = '../data/raw/airbnb.csv'

raw_df = load_data(path)

In [3]:
raw_df.head()

,Unnamed: 0,id,name,rating,reviews,host_name,host_id,address,features,amenities,...,price,country,bathrooms,beds,guests,toiles,bedrooms,studios,checkin,checkout
0,0,49849504,Perla bungalov,4.71,64,Mehmetcan,357334205.0,"Kartepe, Kocaeli, Turkey","2 guests,2 bedrooms,1 bed,1 bathroom","Mountain view,Valley view,Lake access,Kitchen,...",...,8078,Turkey,1,1,2,0,2,0,Flexible,12 00 pm
1,1,50891766,Authentic Beach Architect Sheltered Villa with...,New,0,Fatih,386223873.0,"Kaş, Antalya, Turkey","4 guests,2 bedrooms,2 beds,2 bathrooms","Kitchen,Wifi,Dedicated workspace,Free parking ...",...,4665,Turkey,2,2,4,0,2,0,4 00 pm - 11 00 pm,10 00 am
2,2,50699164,cottages sataplia,4.85,68,Giorgi,409690853.0,"Imereti, Georgia","4 guests,1 bedroom,3 beds,1 bathroom","Mountain view,Kitchen,Wifi,Dedicated workspace...",...,5991,Georgia,1,3,4,0,1,0,After 1 00 pm,12 00 pm
3,3,49871422,Sapanca Breathable Bungalow,5.0,13,Melih,401873242.0,"Sapanca, Sakarya, Turkey","4 guests,1 bedroom,2 beds,1 bathroom","Mountain view,Valley view,Kitchen,Wifi,Free pa...",...,11339,Turkey,1,2,4,0,1,0,After 2 00 pm,12 00 pm
4,4,51245886,Bungalov Ev 2,New,0,Arp Sapanca,414884116.0,"Sapanca, Sakarya, Turkey","2 guests,1 bedroom,1 bed,1 bathroom","Kitchen,Wifi,Free parking on premises,TV,Air c...",...,6673,Turkey,1,1,2,0,1,0,After 2 00 pm,12 00 pm

In [4]:
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12805 entries, 0 to 12804
Data columns (total 23 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    12805 non-null  int64
 1   id            12805 non-null  int64
 2   name          12805 non-null  object
 3   rating        12805 non-null  object
 4   reviews       12805 non-null  object
 5   host_name     12797 non-null  object
 6   host_id       12805 non-null  float64
 7   address       12805 non-null  object
 8   features      12805 non-null  object
 9   amenities     12805 non-null  object
 10  safety_rules  12805 non-null  object
 11  hourse_rules  12805 non-null  object
 12  img_links     12805 non-null  object
 13  price         12805 non-null  int64
 14  country       12805 non-null  object
 15  bathrooms     12805 non-null  int64
 16  beds          12805 non-null  int64
 17  guests        12805 non-null  int64
 18  toiles        12805 non-null  int64
 19  bedrooms      12805 non-null  int64
 20  studios       12805 non-null  int64
 21  checkin       12005 non-null  object
 22  checkout      10355 non-null  object
dtypes: float64(1), int64(9), object(13)
memory usage: 2.2+ MB

In [5]:
raw_df.drop(columns=['Unnamed: 0', 'id', 'name', 'host_name', 'host_id', 'features', 'safety_rules', 'hourse_rules', 'img_links', 'checkin', 'checkout'], inplace=True)

In [6]:
raw_df

,rating,reviews,address,amenities,price,country,bathrooms,beds,guests,toiles,bedrooms,studios
0,4.71,64,"Kartepe, Kocaeli, Turkey","Mountain view,Valley view,Lake access,Kitchen,...",8078,Turkey,1,1,2,0,2,0
1,New,0,"Kaş, Antalya, Turkey","Kitchen,Wifi,Dedicated workspace,Free parking ...",4665,Turkey,2,2,4,0,2,0
2,4.85,68,"Imereti, Georgia","Mountain view,Kitchen,Wifi,Dedicated workspace...",5991,Georgia,1,3,4,0,1,0
3,5.0,13,"Sapanca, Sakarya, Turkey","Mountain view,Valley view,Kitchen,Wifi,Free pa...",11339,Turkey,1,2,4,0,1,0
4,New,0,"Sapanca, Sakarya, Turkey","Kitchen,Wifi,Free parking on premises,TV,Air c...",6673,Turkey,1,1,2,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
12800,4.94,16,"Imhoe-myeon, Jindo, South Jeolla Province, Sou...","Kitchen,Wifi,Free parking on premises,Private ...",4288,South Korea,8,0,4,0,0,0
12801,4.67,6,"Gianyar, Indonesia","Wifi,Free on-street parking,Air conditioning,G...",15200,Indonesia,0,1,2,1,1,0
12802,4.67,3,"Kabale, Uganda","Wifi,Breakfast,Long-term stays allowed,Unavail...",9103,Uganda,1,2,2,0,1,0
12803,4.86,7,"Gunung Sari, Nusa Tenggara Barat, Indonesia","Kitchen,Wifi,Dedicated workspace,Free parking ...",42262,Indonesia,2,4,8,0,2,0
12804,4.85,13,"Uruma, Okinawa, Japan","Sea view,Beach access – Beachfront,Kitchen,Wif...",9909,Japan,1,2,5,0,1,0

In [8]:
unique_address = raw_df["address"].value_counts().reset_index().sort_values("count", ascending=False)

In [9]:
unique_address

                                          address  count
0                 Manali, Himachal Pradesh, India    179
1                         New Delhi, Delhi, India    174
2             Gudauri, Mtskheta-Mtianeti, Georgia    121
3                     Pantelleria, Sicilia, Italy    114
4                        Sapanca, Sakarya, Turkey     99
...                                           ...    ...
3026                       Cherasco, Cuneo, Italy      1
3025       Banjar, Jibhi, Himachal Pradesh, India      1
3024              Mabini, Calabarzon, Philippines      1
3023                     Kodagu, Karnataka, India      1
6286  Gunung Sari, Nusa Tenggara Barat, Indonesia      1

[6287 rows x 2 columns]

In [10]:
geocode_results = {}

In [12]:
from src.utils.open_cage_geocode import get_coordinates
import time

In [14]:
for address in unique_address["address"]:
    try:
        lat, lng = get_coordinates(address)  # Zavolanie tvojej funkcie
        geocode_results[address] = (lat, lng)
    except ValueError as e:
        # Ak funkcia zlyhá, pridaj None a pokračuj
        print(e)
        geocode_results[address] = (None, None)

    # Obmedzenie rýchlosti API volania (napr. 2 požiadavky za sekundu)
    time.sleep(0.5)

RateLimitExceededError: You have used the requests available on your plan. Please purchase more if you wish to continue: https://opencagedata.com/pricing

In [18]:
# Zobrazenie výsledného datasetu
print(geocode_results)

{'address': (25.4769352, 56.3612935), 'count': (None, None), 'Manali, Himachal Pradesh, India': (32.2454608, 77.1872926), 'New Delhi, Delhi, India': (28.6430858, 77.2192671), 'Gudauri, Mtskheta-Mtianeti, Georgia': (42.4765577, 44.4770286), 'Pantelleria, Sicilia, Italy': (36.8314576, 11.9450395), 'Sapanca, Sakarya, Turkey': (40.6930538, 30.27344), 'Trinidad, Sancti Spíritus, Cuba': (21.8052055, -79.9845797), 'Rishikesh, Uttarakhand, India': (30.1086537, 78.2916193), 'Gudauri, Georgia': (42.4765577, 44.4770286), 'Pantelleria, Sicily, Italy': (36.8314576, 11.9450395), 'Fethiye, Muğla, Turkey': (36.6221019, 29.1153234), 'Mumbai, Maharashtra, India': (19.054999, 72.8692035), 'Marrakesh, Marrakesh-Safi, Morocco': (31.6258257, -7.9891608), 'Kaş, Antalya, Turkey': (36.1993752, 29.6413365), 'Bakuriani, Samtskhe-Javakheti, Georgia': (41.7510862, 43.5280065), 'Gurugram, Haryana, India': (28.4646148, 77.0299194), 'Wadi Rum Village, Aqaba Governorate, Jordan': (31.0, 36.0), 'Jibhi, Himachal Pradesh, India': (31.5922834, 77.3526223), 'Tambon Rawai, Chang Wat Phuket, Thailand': (7.89059, 98.3981), 'Candolim, Goa, India': (15.5201532, 73.7659422), 'Thira, Greece': (36.4071112, 25.4566637), 'Tambon Karon, Chang Wat Phuket, Thailand': (7.89059, 98.3981), 'Mussoorie, Uttarakhand, India': (30.4569012, 78.0782906), 'Kasauli, Himachal Pradesh, India': (30.8999479, 76.9619744), 'Calangute, Goa, India': (15.545594, 73.7646182), 'Marrakech, Marrakech-Safi, Morocco': (31.6258257, -7.9891608), 'Alappuzha, Kerala, India': (9.5006651, 76.4124143), 'Dubai, United Arab Emirates': (25.0742823, 55.1885387), 'Srinagar, India': (34.0747444, 74.8204443), 'Marrakesh, Marrakesh-Tensift-El Haouz, Morocco': (35.69834, -5.44015), 'Udaipur, Rajasthan, India': (24.578721, 73.6862571), 'Lonavla, Maharashtra, India': (18.7618607, 73.4038888), 'Mikonos, Greece': (37.4513936, 25.3923149), 'Paris, Île-de-France, France': (48.830919, 2.376158), 'Arambol, Goa, India': (15.6878815, 73.7055986), 'Jaipur, Rajasthan, India': (26.9154576, 75.8189817), 'Kodaikanal, Tamil Nadu, India': (10.233712, 77.4919719), 'Arpora, Goa, India': (15.5630974, 73.7640368), 'Santorini, Greece': (36.4071112, 25.4566637), 'Cape Town, Western Cape, South Africa': (-33.9288301, 18.4172197), 'Shimla, Himachal Pradesh, India': (31.1041526, 77.1709729), 'Martina Franca, Puglia, Italy, Italy': (40.70142, 17.33304), 'Kullu, Himachal Pradesh, India': (31.9578974, 77.1089232), 'Marmaris, Muğla, Turkey': (36.8522547, 28.2742661), 'Bhimtal, Uttarakhand, India': (29.3506056, 79.5541717), 'Ji’an Township, Taiwan': (24.0, 121.0), 'Dharamshala, Himachal Pradesh, India': (32.2143039, 76.3196717), 'Ubud, Bali, Indonesia': (-8.5068977, 115.2622931), 'Tambon Patong, Chang Wat Phuket, Thailand': (7.89059, 98.3981), 'Bodrum, Muğla, Turkey': (37.0343987, 27.430651), 'Dehradun, Uttarakhand, India': (30.3255646, 78.0436813), 'Ostuni, Puglia, Italy, Italy': (40.72484, 17.57922), 'Hikkaduwa, Southern Province, Sri Lanka': (6.140753, 80.1028181), 'Anjuna, Goa, India': (15.5850408, 73.7438151), 'Kittilä, Finland': (67.651985, 24.9095086), 'Nainital, Uttarakhand, India': (29.2949949, 79.4162511), 'Mesaria, Greece': (36.398702, 25.4467341), 'Beograd, Serbia': (44.8178131, 20.4568974), 'Srinagar, Jammu and Kashmir, India': (34.0747444, 74.8204443), 'Banjar, Himachal Pradesh, India': (31.6351335, 77.4352861), 'Weligama, Southern Province, Sri Lanka': (5.9754333, 80.4295612), 'Kamari, Greece': (36.3761502, 25.4806336), 'Vestvågøy, Nordland, Norway': (68.1607217, 13.784107), 'Hengchun Township, Taiwan': (24.0, 121.0), 'Naggar, Himachal Pradesh, India': (32.1132488, 77.1640042), 'Tbilisi, Georgia': (41.6934591, 44.8014495), 'Rawai, Phuket, Thailand': (7.7758136, 98.3277162), 'Ulaanbaatar, Mongolia': (47.9184676, 106.9177016), 'Sigiriya, Central Province, Sri Lanka': (7.9498094, 80.7463471), 'Agra, Uttar Pradesh, India': (27.1752554, 78.0098161), 'Siolim, Goa, India': (15.6270222, 73.7656851), 'Thera, Greece': (36.4071112, 25.4566637), 'Pyrgos Kallistis, Greece': (36.3826042, 25.4501541), 'Jaisalmer, Rajasthan, India': (27.0264162, 70.777512), 'Hualien City, Taiwan': (23.982074, 121.60681), 'Cavinti, Calabarzon, Philippines': (14.2453833, 121.5070018), 'Mandrem, Goa, India': (15.6551117, 73.7197877), 'Scauri, Sicilia, Italy': (36.7667451, 11.9721206), 'Emporio, Greece': (36.3571658, 25.4461188), 'Marrakech, Marrakech-Tensift-Al Haouz, Morocco': (31.63416, -7.99994), 'Ceglie Messapica, Puglia, Italy, Italy': (40.6462, 17.51661), 'Locorotondo, Puglia, Italy, Italy': (40.75661, 17.32392), 'Alberobello, Puglia, Italy, Italy': (40.78448, 17.23618), '京都市, 京都府, Japan': (35.0115754, 135.7681441), 'Mtskheta-Mtianeti, Georgia': (42.2290312, 44.8569963), 'North Goa, Goa, India': (15.6044413, 74.0017241), 'Megalochori, Greece': (36.3763939, 25.4317299), 'Langkawi, Kedah, Malaysia': (6.3700386, 99.7928634), 'Imerovigli, Greece': (36.4325579, 25.4228307), 'El Nido, MIMAROPA, Philippines': (11.1800395, 119.390496), 'Gapyeong-eup, Gapyeong-gun, Gyeonggi Province, South Korea': (37.825338, 127.5166062), 'Beyoğlu, İstanbul, Turkey': (41.0284233, 28.9736808), 'Cienfuegos, Cuba': (22.1459864, -80.4530775), 'Santa Clara, Villa Clara, Cuba': (22.406628, -79.9651013), 'Ren’ai Township, Taiwan': (24.024429, 121.133543), 'Phuket, Thailand': (7.9366015, 98.3529292), 'Panaji, Goa, India': (15.4989946, 73.8282141), 'Galle, Southern Province, Sri Lanka': (6.0328139, 80.214955), 'Haridwar, Uttarakhand, India': (29.9384473, 78.1452985), 'Kecamatan Kuta Selatan, Bali, Indonesia': (-8.5, 115.0), 'Canacona, Goa, India': (15.0069072, 74.0570639), 'Cisternino, Puglia, Italy, Italy': (40.74326, 17.42587), 'Taitung City, Taiwan': (22.7560447, 121.1456538), 'Tandi, Himachal Pradesh, India': (32.556087, 76.9747132), 'Kecamatan Ubud, Bali, Indonesia': (-8.5119399, 115.2378113), 'Marrakech, Marrakesh-Safi, Morocco': (31.6305935, -8.0171313), 'Rovaniemi, Finland': (66.5025657, 25.73122), 'Goa, India': (15.3004543, 74.0855134), 'Paros, Greece': (37.0651494, 25.1919784), 'Vothonas, Greece': (36.3937862, 25.4510674), 'Greater London, England, United Kingdom': (51.4893335, -0.1440551), 'Göreme Belediyesi, Nevşehir, Turkey': (38.6445768, 34.8291408), 'Sainj, Himachal Pradesh, India': (31.7796376, 77.5258661), 'Vagator, Goa, India': (15.5985735, 73.7408126), 'Pirgos Kallistis, Greece': (36.3826042, 25.4501541), 'India': (22.3511148, 78.6677428), 'Pantelleria, Italy': (36.8314576, 11.9450395), 'Merzouga, Drâa-Tafilalet, Morocco': (31.0999166, -4.0140878), 'Kuta Utara, Bali, Indonesia': (-8.6434167, 115.1609766), 'Fès, Fès-Meknès, Morocco': (34.0346534, -5.0161926), 'Gurgaon, Haryana, India': (28.4646148, 77.0299194), 'Fes, Fez-Meknès, Morocco': (34.0346534, -5.0161926), 'Oia, Greece': (36.4622122, 25.3757257), 'Kuta, Bali, Indonesia': (-8.7278354, 115.1730049), 'Eilat, South District, Israel': (29.5569348, 34.9497949), 'Fes, Fes-Boulemane, Morocco': (34.03715, -4.9998), 'Kumarakom, Kerala, India': (9.5949953, 76.4302599), 'Selva di Fasano, Puglia, Italy, Italy': (40.8279, 17.32201), 'Exo Gonia, Greece': (36.3879757, 25.4578667), 'Daegwalnyeong-myeon, Pyeongchang-gun, Gangwon Province, South Korea': (36.5, 127.75), 'Assagao, Goa, India': (15.5981002, 73.7721529), 'Kolari, Finland': (67.3303348, 23.7814738), 'Göreme, Nevşehir, Turkey': (38.642089, 34.8296234), 'Khamma, Sicilia, Italy': (36.8008302, 12.0319979), 'Tanay, Calabarzon, Philippines': (14.4985359, 121.2856331), 'Thera, Egeo, Greece': (39.0, 22.0), 'Camagüey, Cuba': (21.3791765, -77.9183681), 'Agonda, Goa, India': (15.0411042, 73.9882421), 'Morjim, Goa, India': (15.6303018, 73.7337021), 'Kyiv, Ukraine': (50.4500336, 30.5241361), 'Mahabaleshwar, Maharashtra, India': (17.9242764, 73.6575799), "T'bilisi, Tbilisi, Georgia": (41.7247085, 44.7166549), 'Baga, Goa, India': (15.5592836, 73.7539656), 'Bansko, Blagoevgrad, Bulgaria': (41.8344086, 23.4841698), 'Vågan, Nordland, Norway': (68.2776871, 14.6630573), 'Fagu, Himachal Pradesh, India': (31.0869772, 77.3033208), 'Hatgal, Khövsgöl, Mongolia': (50.4442293, 100.1579353), 'Chiang Mai, Thailand': (18.7882778, 98.9858802), 'Montegufoni, Tuscany, Italy': (43.670563, 11.0892811), 'Colva, Goa, India': (15.278266, 73.9197099), 'Carovigno, Puglia, Italy, Italy': (40.70626, 17.65847), 'San Michele salentino, Puglia, Italy, Italy': (40.63163, 17.63254), 'New Delhi, DL, India': (28.6430858, 77.2192671), 'Tambon Chalong, Chang Wat Phuket, Thailand': (7.89059, 98.3981), 'Solan, Himachal Pradesh, India': (30.9077569, 77.1023645), 'Greater Noida, Uttar Pradesh, India': (28.4670734, 77.5137649), 'Rome, Lazio, Italy': (41.8933203, 12.4829321), 'Kent, England, United Kingdom': (51.2070748, 0.7210362), 'Sawai Madhopur, Rajasthan, India': (26.1137182, 76.4240637), 'Marrakesh, Morocco': (31.6258257, -7.9891608), 'San Vito dei Normanni, Puglia, Italy, Italy': (40.65642, 17.70814), 'Arugam Bay, Eastern Province, Sri Lanka': (6.8466228, 81.8305531), 'Seminyak, Bali, Indonesia': (-8.6908357, 115.1641975), 'Gildeskål, Nordland, Norway': (67.0060361, 13.9437332), 'Kochi, Kerala, India': (9.9674277, 76.2454436), 'Fairbanks, Alaska, United States': (64.837845, -147.716675), 'Ko Samui, Chang Wat Surat Thani, Thailand': (9.14011, 99.33311), 'Monopoli, Puglia, Italy, Italy': (40.94918, 17.29717), 'Ramnagar, Uttarakhand, India': (29.394835, 79.126934), 'Kasol, Himachal Pradesh, India': (32.0104317, 77.3166036), 'West Central District, Tainan City, Taiwan': (22.99083, 120.21333), 'Noida, Uttar Pradesh, India': (28.5706333, 77.3272147), 'Kecamatan Kuta Utara, Bali, Indonesia': (-8.5, 115.0), 'Mukteshwar, Uttarakhand, India': (29.4720782, 79.6480433), 'Tromsø, Troms, Norway': (69.6516345, 18.9558585), 'Munnar, Kerala, India': (10.0869959, 77.0600915), 'Hassilabied, Drâa-Tafilalet, Morocco': (31.1383018, -4.0259002), 'Naxos, Greece': (37.0600105, 25.4707567), 'Tambon Sala Dan, Chang Wat Krabi, Thailand': (8.07257, 98.91052), 'Emporio, Egeo, Greece': (39.0, 22.0), 'Pushkar, Rajasthan, India': (26.4876472, 74.5578484), 'Tambon Wichit, Chang Wat Phuket, Thailand': (7.89059, 98.3981), 'Maldives': (3.7203503, 73.2244152), 'Unawatuna, Southern Province, Sri Lanka': (6.0201774, 80.2474836), 'Florence, Toscana, Italy': (43.7697955, 11.2556404), 'Mitzpe Ramon, South District, Israel': (30.6124329, 34.8018727), 'Cavelossim, Goa, India': (15.1845618, 73.9456314), 'Bansko, Blagoevgrad Province, Bulgaria': (42.66667, 25.25), 'Tel Aviv-Yafo, Tel Aviv District, Israel': (32.0852997, 34.7818064), 'Martina Franca, Apulia, Italy': (40.7042378, 17.3399908), 'Monselice, Veneto, Italy': (45.2417684, 11.7508534), 'Mhamid, Drâa-Tafilalet, Morocco': (29.8249017, -5.7198185), 'Jodhpur, Rajasthan, India': (26.2967719, 73.0351433), 'Ostuni, Apulia, Italy': (40.727631, 17.576406), 'Varadero, Matanzas, Cuba': (23.149578, -81.260025), 'Berlin, Germany': (52.510885, 13.3989367), 'Nairobi, Nairobi County, Kenya': (-1.3026148, 36.828842), 'Santiago de Cuba, Cuba': (20.0214263, -75.8294928), 'Ürgüp, Nevşehir, Turkey': (38.6300508, 34.9116025), 'Fira, Greece': (36.4149227, 25.4324527), 'Gunnae-myeon, Pocheon-si, Gyeonggi Province, South Korea': (37.87723, 127.22198), 'Malé, Male, Maldives': (4.1747188, 73.5101899), 'Kangra, Himachal Pradesh, India': (32.0768665, 76.2985872), 'Karterádos, Greece': (36.4111617, 25.4460945), 'Mirissa, Southern Province, Sri Lanka': (5.9493634, 80.4558128), 'Trinidad, Sancti Spiritus, Cuba': (21.8052055, -79.9845797), 'Kolkata, West Bengal, India': (22.5726459, 88.3638953), 'Holguín, Cuba': (20.8869704, -76.2591995), 'Selat, Bali, Indonesia': (-8.4356426, 115.4754816), 'North Yorkshire, England, United Kingdom': (54.1345327, -1.4986285), 'Remedios, Villa Clara, Cuba': (22.4950138, -79.5448653), 'Vrindavan, Uttar Pradesh, India': (27.5753726, 77.6938045), 'Mestia, Samegrelo-Zemo Svaneti, Georgia': (43.0437615, 42.7244532), 'Delhi, India': (28.6273928, 77.1716954), 'Negombo, Western Province, Sri Lanka': (7.2094282, 79.833117), 'Nerul, Goa, India': (15.520719, 73.7838406), 'Belgrade, Serbia': (44.8178131, 20.4568974), 'Oia, Egeo, Greece': (39.0, 22.0), 'Madrid, Comunidad de Madrid, Spain': (40.4167047, -3.7035825), 'Tambon Choeng Thale, Chang Wat Phuket, Thailand': (7.89059, 98.3981), 'Muang Pattaya, Chang Wat Chon Buri, Thailand': (13.3622, 100.98345), 'Mhamid, Souss-Massa-Draa, Morocco': (29.82, -5.72), 'Bir, Himachal Pradesh, India': (32.0445234, 76.7255115), 'Varkala, Kerala, India': (8.7342288, 76.7257086), 'Santorini, Cyclades, Greece': (36.39963, 25.42081), 'Marrakech, Morocco': (31.6258257, -7.9891608), 'Luxor, Luxor Governorate, Egypt': (25.702096, 32.647186), 'Ko Samui District, Surat Thani, Thailand': (9.53567, 99.93567), 'Ashvem Beach, Goa, India': (15.649388, 73.7154295), 'Nashik, Maharashtra, India': (20.0112475, 73.7902364), 'Pyoseon-myeon, Seogwipo, Jeju Province, South Korea': (33.3504543, 126.794049), 'Kintamani, Bali, Indonesia': (-8.2505623, 115.3330086), 'Quairah District, Aqaba Governorate, Jordan': (31.0, 36.0), 'Kyōto-shi, Kyōto-fu, Japan': (35.0115754, 135.7681441), 'Mikonos, Egeo, Greece': (39.0, 22.0), 'Karon, Phuket, Thailand': (7.84752, 98.2981141), 'New Delhi, India': (28.6430858, 77.2192671), 'Kyoto, Kyoto Prefecture, Japan': (35.0115754, 135.7681441), 'Magong City, Taiwan': (23.5663766, 119.5784885), 'Batumi, Adjara, Georgia': (41.6241427, 41.6249897), 'Budapest, Hungary': (47.4813896, 19.1460941), 'Thành phố Đà Lạt, Lâm Đồng, Vietnam': (11.9402416, 108.4375758), 'Ahmedabad, Gujarat, India': (23.0215374, 72.5800568), 'Gujwa-eup, Jeju-si, Jeju Province, South Korea': (33.51662, 126.81055), 'Kuusamo, Finland': (65.9645637, 29.1883283), 'Nuwara Eliya, Central Province, Sri Lanka': (7.012402, 80.7571612), 'Predeal, Județul Brașov, Romania': (45.64861, 25.60613), 'Ostuni, Italy': (40.727631, 17.576406), 'Pune, Maharashtra, India': (18.5213738, 73.8545071), 'La Boca, Sancti Spíritus, Cuba': (21.7990139, -80.0339601), 'Rodos, Greece': (36.1725297, 27.9194016), 'Cát Hải, Hải Phòng, Vietnam': (20.7969968, 106.8905903), 'Buk-myeon, Gapyeong-gun, Gyeonggi Province, South Korea': (37.92665, 127.51093), 'Borovets, Sofiyska oblast, Bulgaria': (42.27067, 23.60562), 'Brașov, Județul Brașov, Romania': (45.64861, 25.60613), 'Mykonos, Greece': (37.4513936, 25.3923149), 'Pantelleria, Trapani, Italy': (36.8314576, 11.9450395), 'Marrakesh, Marrakesh-Tensift-Al Haouz, Morocco': (31.34083, -7.91076), 'Krong Siem Reap, Siem Reap Province, Cambodia': (13.0, 105.0), 'Jerusalem, Jerusalem District, Israel': (31.7788242, 35.2257626), 'Tromsø, Troms og Finnmark, Norway': (70.0815, 29.7358), 'Centinarola, Marche, Italy': (43.8314394, 12.9895407), 'Baguio, Cordillera Administrative Region, Philippines': (16.4119905, 120.5933719), 'Coron, MIMAROPA, Philippines': (11.9985507, 120.2051611), 'Baracoa, Guantánamo, Cuba': (20.3477869, -74.4968647), 'Varadero, Cuba': (23.149578, -81.260025), 'Uttarakhand, India': (30.0417376, 79.089691), 'Fuxing District, Taoyuan City, Taiwan': (24.8153769, 121.351898), 'Athina, Greece': (37.9755648, 23.7348324), 'Netanya, Center District, Israel': (32.3286181, 34.8566246), 'Puli Township, Taiwan': (23.9666667, 120.9691462), 'Srinagar, Jammu & Kashmir, India': (34.0747444, 74.8204443), 'Dehiwala-Mount Lavinia, Western Province, Sri Lanka': (6.8369601, 79.8672866), 'Seririt, Bali, Indonesia': (-8.193144, 114.9342652), 'Gangtok, Sikkim, India': (27.329046, 88.6122673), 'Sosan, Himachal Pradesh, India': (31.91667, 77.25), 'Mapo-gu, Seoul, South Korea': (37.566571, 126.9015317), 'Hoàn Kiếm, Hà Nội, Vietnam': (21.0281683, 105.8511514), 'Coron, Palawan, MIMAROPA, Philippines': (11.9985507, 120.2051611), 'Liuqiu Township, Taiwan': (24.0, 121.0), 'Sydney, New South Wales, Australia': (-33.8698439, 151.2082848), 'North District, Tainan City, Taiwan': (22.99083, 120.21333), 'Madonna delle Grazie, Sicilia, Italy': (36.7984477, 11.949969), 'Tambon Bo Put, Chang Wat Surat Thani, Thailand': (9.14011, 99.33311), 'Lonavala, Maharashtra, India': (18.7548563, 73.4016729), 'Raison, Himachal Pradesh, India': (32.0532262, 77.1335198), 'Sala Dan, Krabi, Thailand': (7.6492843, 99.0378486), 'Ko Samui, Surat Thani, Thailand': (9.5013944, 99.9956193), 'West Sussex, England, United Kingdom': (51.0, -0.416667), 'Bangkok, Krung Thep Maha Nakhon, Thailand': (13.7862751, 100.5125577), 'Thailand': (14.8971921, 100.83273), 'Amphoe Ko Lanta, Chang Wat Krabi, Thailand': (8.07257, 98.91052), 'Aswan, Aswan Governorate, Egypt': (24.091071, 32.897306), 'Abu Dhabi, United Arab Emirates': (24.4538352, 54.3774014), 'Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia': (3.1516964, 101.6942371), 'Nashville, Tennessee, United States': (36.1622767, -86.7742984), 'Dambulla, Central Province, Sri Lanka': (7.8742031, 80.6510917), 'Kotkhai, Himachal Pradesh, India': (31.1569042, 77.5310257), 'Bengaluru, Karnataka, India': (12.9767936, 77.590082), 'Kamień Pomorski, Województwo zachodniopomorskie, Poland': (53.9653947, 14.7728556), 'Tangalle, Southern Province, Sri Lanka': (6.0219509, 80.7959935), '花蓮市, 花蓮縣, Taiwan': (23.982074, 121.60681), 'Chamonix-Mont-Blanc, Auvergne-Rhône-Alpes, France': (45.9246705, 6.8727506), 'Flakstad, Nordland, Norway': (68.1204683, 13.0496376), 'Mustafapaşa, Nevşehir, Turkey': (38.5833959, 34.8969158), 'Klil, North District, Israel': (32.9855303, 35.2004778), 'Altomonte, Cosenza, Italy': (39.6978818, 16.1271277), 'Todi, Umbria, Italy': (42.7824434, 12.4062554), 'Ko Lanta Yai, Krabi, Thailand': (7.559842, 99.0572888), 'Narkand, Himachal Pradesh, India': (31.91667, 77.25), 'Tambon Ao Nang, Chang Wat Krabi, Thailand': (8.07257, 98.91052), 'Ngũ Hành Sơn, Đà Nẵng, Vietnam': (16.00402, 108.2627745), 'Lugu Township, Taiwan': (23.74585, 120.7535833), 'Ko Lanta, Krabi, Thailand': (7.559842, 99.0572888), "Vorokhta, Ivano-Frankivs'ka oblast, Ukraine": (48.28459, 24.56536), 'Essaouira, Marrakech-Safi, Morocco': (31.5118281, -9.7620903), 'Nagaon, Maharashtra, India': (16.9213238, 74.3514776), 'Rutten, Flevoland, Netherlands': (52.8051952, 5.6973664), 'Bayamo, Granma, Cuba': (20.3734145, -76.6494244), 'Behren-Lübchin, Mecklenburg-Vorpommern, Germany': (54.0291146, 12.6646378), 'Tinos, Greece': (37.6017133, 25.1540218), 'Perugia, Umbria, Italy': (43.1070321, 12.4029962), 'Aqaba Governorate, Jordan': (31.0, 36.0), 'Ko Pha Ngan, Surat Thani, Thailand': (9.7349503, 100.0305711), 'Pelkosenniemi, Finland': (67.1095969, 27.5118116), 'Ella, Uva Province, Sri Lanka': (6.8736058, 81.0489927), 'Yelagiri, Tamil Nadu, India': (12.589316, 78.6323577), 'Sarpi, Adjara, Georgia': (41.5218985, 41.5489175), 'Zuozhen District, Tainan City, Taiwan': (22.99083, 120.21333), 'Jinning Township, Taiwan': (24.4507983, 118.335033), 'Karimkunnam, Kerala, India': (9.8498459, 76.6877885), 'Lauterbrunnen, Bern, Switzerland': (46.5939043, 7.9078016), 'Finikia, Egeo, Greece': (39.0, 22.0), 'Minamiawaji, Hyogo, Japan': (34.2945545, 134.7798281), 'Chadiyari, Manali, Himachal Pradesh, India': (32.2574, 77.17481), 'Sang-myeon, Gapyeong-gun, Gyeonggi Province, South Korea': (37.79378, 127.33944), 'Trincomalee, Eastern Province, Sri Lanka': (8.576425, 81.2344952), 'دبي, United Arab Emirates': (25.0742823, 55.1885387), 'Uluwatu, Bali, Indonesia': (-8.767766, 115.1740095), 'Kuta Selatan, Bali, Indonesia': (-8.8014264, 115.1766929), 'Mandaluyong, Metro Manila, Philippines': (14.5774392, 121.0338973), 'Seosin-myeon, Hwaseong-si, Gyeonggi Province, South Korea': (37.1690451, 126.7114352), 'Kutaisi, Imereti, Georgia': (42.2716078, 42.7054475), 'Oia, Santorini, Greece': (36.4622122, 25.3757257), 'ตำบล ศาลาด่าน, กระบี่, Thailand': (8.07257, 98.91052), 'Aewol-eup, Cheju, Jeju Province, South Korea': (33.45079, 126.3752), 'Xiulin Township, Taiwan': (23.7265482, 120.7030736), 'Seongsan-eup, Seogwipo, Jeju Province, South Korea': (33.41805, 126.88147), 'Locorotondo, Apulia, Italy': (40.75523, 17.3265), '馬公市, Taiwan': (23.5663766, 119.5784885), 'Ahangama, Southern Province, Sri Lanka': (5.9735163, 80.3622999), 'Seongsan-eup, Seogwipo-si, Jeju Province, South Korea': (33.4

In [20]:
raw_df['latitude'] = raw_df['address'].map(lambda addr: geocode_results.get(addr, (None, None))[0])
raw_df['longitude'] = raw_df['address'].map(lambda addr: geocode_results.get(addr, (None, None))[1])

# Výsledný dataset
raw_df.head()

,rating,reviews,address,amenities,price,country,bathrooms,beds,guests,toiles,bedrooms,studios,latitude,longitude
0,4.71,64,"Kartepe, Kocaeli, Turkey","Mountain view,Valley view,Lake access,Kitchen,...",8078,Turkey,1,1,2,0,2,0,40.745436,30.011283
1,New,0,"Kaş, Antalya, Turkey","Kitchen,Wifi,Dedicated workspace,Free parking ...",4665,Turkey,2,2,4,0,2,0,36.199375,29.641337
2,4.85,68,"Imereti, Georgia","Mountain view,Kitchen,Wifi,Dedicated workspace...",5991,Georgia,1,3,4,0,1,0,42.187560,42.952155
3,5.0,13,"Sapanca, Sakarya, Turkey","Mountain view,Valley view,Kitchen,Wifi,Free pa...",11339,Turkey,1,2,4,0,1,0,40.693054,30.273440
4,New,0,"Sapanca, Sakarya, Turkey","Kitchen,Wifi,Free parking on premises,TV,Air c...",6673,Turkey,1,1,2,0,1,0,40.693054,30.273440

In [22]:
raw_df['latitude'].isna().sum()

3797

In [23]:
raw_df['longitude'].isna().sum()

3797

In [24]:
raw_df.dropna(subset=['latitude', 'longitude'], inplace=True)

In [26]:
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9008 entries, 0 to 12804
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   rating     9008 non-null   object
 1   reviews    9008 non-null   object
 2   address    9008 non-null   object
 3   amenities  9008 non-null   object
 4   price      9008 non-null   int64
 5   country    9008 non-null   object
 6   bathrooms  9008 non-null   int64
 7   beds       9008 non-null   int64
 8   guests     9008 non-null   int64
 9   toiles     9008 non-null   int64
 10  bedrooms   9008 non-null   int64
 11  studios    9008 non-null   int64
 12  latitude   9008 non-null   float64
 13  longitude  9008 non-null   float64
dtypes: float64(2), int64(7), object(5)
memory usage: 1.0+ MB

In [27]:
raw_df.drop(columns=["address"], inplace=True)

In [31]:
raw_df['rating'].replace("New", 0)

0        4.71
1           0
2        4.85
3         5.0
4           0
         ...
12797     5.0
12799       0
12800    4.94
12801    4.67
12804    4.85
Name: rating, Length: 9008, dtype: object

In [36]:
raw_df['rating'] = raw_df['rating'].replace("New", 0).astype(float).fillna(0)

In [37]:
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9008 entries, 0 to 12804
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   rating     9008 non-null   float64
 1   reviews    9008 non-null   object
 2   amenities  9008 non-null   object
 3   price      9008 non-null   int64
 4   country    9008 non-null   object
 5   bathrooms  9008 non-null   int64
 6   beds       9008 non-null   int64
 7   guests     9008 non-null   int64
 8   toiles     9008 non-null   int64
 9   bedrooms   9008 non-null   int64
 10  studios    9008 non-null   int64
 11  latitude   9008 non-null   float64
 12  longitude  9008 non-null   float64
dtypes: float64(3), int64(7), object(3)
memory usage: 985.2+ KB

In [40]:
raw_df['reviews'] = raw_df['reviews'].str.replace(',', '').astype(float)

In [41]:
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9008 entries, 0 to 12804
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   rating     9008 non-null   float64
 1   reviews    9008 non-null   float64
 2   amenities  9008 non-null   object
 3   price      9008 non-null   int64
 4   country    9008 non-null   object
 5   bathrooms  9008 non-null   int64
 6   beds       9008 non-null   int64
 7   guests     9008 non-null   int64
 8   toiles     9008 non-null   int64
 9   bedrooms   9008 non-null   int64
 10  studios    9008 non-null   int64
 11  latitude   9008 non-null   float64
 12  longitude  9008 non-null   float64
dtypes: float64(4), int64(7), object(2)
memory usage: 985.2+ KB

In [43]:
raw_df.head()

,rating,reviews,amenities,price,country,bathrooms,beds,guests,toiles,bedrooms,studios,latitude,longitude
0,4.71,64.0,"Mountain view,Valley view,Lake access,Kitchen,...",8078,Turkey,1,1,2,0,2,0,40.745436,30.011283
1,0.00,0.0,"Kitchen,Wifi,Dedicated workspace,Free parking ...",4665,Turkey,2,2,4,0,2,0,36.199375,29.641337
2,4.85,68.0,"Mountain view,Kitchen,Wifi,Dedicated workspace...",5991,Georgia,1,3,4,0,1,0,42.187560,42.952155
3,5.00,13.0,"Mountain view,Valley view,Kitchen,Wifi,Free pa...",11339,Turkey,1,2,4,0,1,0,40.693054,30.273440
4,0.00,0.0,"Kitchen,Wifi,Free parking on premises,TV,Air c...",6673,Turkey,1,1,2,0,1,0,40.693054,30.273440

In [47]:

data_with_geo = raw_df.to_csv('../data/processed/processed_data_geo.csv', index=False) 

data_with_geo